# Generated by Django 4.0.6 on 2022-07-14 11:20

import autoslug.fields
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=users.models.User.instance, unique_with=['username', 'email']),
        ),
    ]
