# Generated by Django 4.0.6 on 2022-08-19 20:16

import autoslug.fields
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=users.models.Profile.__str__, unique_with=['user']),
        ),
    ]
