# Generated by Django 4.0.6 on 2022-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('preview', models.CharField(max_length=250, verbose_name='Preview')),
                ('content', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Publish date')),
            ],
        ),
    ]
