# Generated by Django 4.0.6 on 2022-07-27 01:35

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import newsapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('preview', models.CharField(max_length=250, verbose_name='Preview')),
                ('content', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Publish date')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=newsapp.models.Articles.instance)),
                ('amount_views', models.IntegerField(default=0, verbose_name='Amount_views')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Publish date')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.articles')),
            ],
        ),
    ]
