# Generated by Django 4.0.6 on 2022-07-16 15:10

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newsapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='articles',
            name='amount_views',
            field=models.IntegerField(null=True, verbose_name='Amount_views'),
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=newsapp.models.Articles.instance),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish date'),
        ),
    ]
