# Generated by Django 4.0.6 on 2022-08-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
