# Generated by Django 4.0.6 on 2022-07-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'News'},
        ),
    ]
