# Generated by Django 4.0.6 on 2022-07-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_articles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='amount_views',
            field=models.IntegerField(null=True, verbose_name='Amount_views'),
        ),
    ]
